### PR TITLE
Clear old entry files

### PR DESCRIPTION
**Pull request by msegers**
This is a potential solution to #3, obviously can use improvements, like support for [hash:10] (any custom hash length number), options which differ from [hash] like chunkhash etc.

I'm not entirely convinced this would be the way to go, let me know what you think? If you believe this could potentially fix things we can expand it, for me this is working rather nicely (I was debugging this.js to see if it clears old files).

### CODE REVIEW

**Comment by firsttris** [comment]
I understood that this contribution adds support for chunkhash and hash:10 to the plugin.

> I'm not entirely convinced this would be the way to go, let me know what you think?

I do not know either. i forced this problem and didn't solve it. 
for me this solution seems rather complex, shouldn't there be an easier way? i don't know.

Can you modify the example project to use chunkhash or hash:10. then i can easily test your contribution :+1:

**Comment by msegers** [comment]
Yes I actually worked on that this afternoon let me update the PR tomorrow.
Or in a few minutes maybe

**Comment by msegers** [comment]
There we go. I do have different formatting. see if you like it.

**Comment by minlare** [comment]
@firsttris - any chance of getting this released?

**Comment by firsttris** [comment]
published with 1.1.0

**Comment by firsttris** [comment]
thx for your contribution :rocket:

**Pull request merged**
